export const pokemonNames = [
  { name: "ditto", id: 1 },
  { name: "pikachu", id: 2 },
  { name: "eevee", id: 3 },
  { name: "charizard", id: 4 },
  { name: "charmander", id: 5 },
  { name: "mewtwo", id: 6 },
  { name: "mew", id: 7 },
  { name: "squirtle", id: 8 },
  { name: "bulbasaur", id: 9 },
  { name: "snorlax", id: 10 },
  { name: "garchomp", id: 11 },
  { name: "lucario", id: 12 },
  { name: "gardevoir", id: 13 },
  { name: "piplup", id: 14 },
  { name: "dialga", id: 15 },
  { name: "palkia", id: 16 },
  { name: "gyarados", id: 17 },
  { name: "blastoise", id: 18 },
];
